// Code generated by sqlc. DO NOT EDIT.

package override

import (
	"github.com/ianberinger/sqlc-testdata/pkg"
	"github.com/lib/pq"
)

type Foo struct {
	Other   string
	Total   int64
	Tags    []string
	ByteSeq []byte
	Retyped pkg.CustomType
	Langs   pq.StringArray
}
